config/routes.rb
Rails.application.routes.draw do

  devise_for :users

   resources :users,only: [:show,:index,:edit,:update] do
     resource :relationships,only: [:create, :destroy]

     member do
       get :following, :followers
     end
   end

  resources :books do
    resource:favorites,only: [:create, :destroy]
    resources:comments,only: [:create, :destroy]
  end

  root 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :comments, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  # フォローする側のリレーションシップ
  has_many :active_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  # N対N　のリレーションシップにはthroughを使う。
  # user.following = user.followed.idとなるようにsourceを設定
  has_many :following, through: :active_relationships, source: :followed
  # フォローされる側のリレーションシップ
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :followed_id
  #N対N　のリレーションシップにはthroughを使う。
  # user.followers = user.follower.idとなるようにsourceを設定
  has_many :followers, through: :passive_relationships, source: :follower

#すでにフォロー済であればtrue返す
  def following?(other_user)
    following.include?(other_user)
  end
# ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end
# ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  attachment :profile_image, destroy: false

  validates :name,  presence: true, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :authenticate_user!

  def show
    @book_find = Book.find(params[:id])
    @book = Book.new
    @book_comment = Comment.new
    @comments = Comment.all
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.comments.new(book_comment_params)
    comment.book_id = book.id
    if comment.save
      redirect_to request.referer
    else
      render 'show'
    end
  end

  def destroy
    Comment.find_by(id: params[:id], book_id: params[:book_id]).destroy

    redirect_to request.referer
  end

  private
  def book_comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = book.favorites.find_by(user_id: current_user.id)
    favorite.destroy
    redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    user = User.find(params[:user_id])
    current_user.follow(user)
    redirect_to request.referer
  end

  def destroy
    user = User.find(params[:user_id])
    current_user.unfollow(user)
    redirect_to request.referer
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      @users = User.all
      render "edit"
    end
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def following
    @user = User.find(params[:id])
  end

  def followers
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book, local:true do |f| %>
  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'col-xs-12 book_title' %>
  </div>

  <div class="field row">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'col-xs-12 book_body' %>
  </div>

  <div class="actions row">
    <%= f.submit class: 'btn btn-primary col-xs-12' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>

    <%= render 'layouts/errors', book: @book %>
		<%= render "books/form", book: @book %>
		<%= link_to "Show", book_path(@book.id) %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<%= render 'layouts/errors', book: @book %>

<div class="row">
	<div class="col-xs-3">


		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/form', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book.id) %></td>
					<td><%= book.body %></td>
					<!--いいね-->
					<%= render 'favorites/btn', book_find: book %>

          <!--いいねここまで-->
          <td>
          	<p class="comment-count">コメント数：<%= book.comments.count %></p>
          </td>

				</tr>
				<% end %>
			</tbody>
		</table>


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @book_find.user %>

		<h2>New book</h2>
		<%= render 'books/form', book: @book %>


	</div>


	<div class="col-xs-9">

		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@book_find.user) do %>
							<%= attachment_image_tag(@book_find.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book_find.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book_find.title, book_path(@book_find) %></td>
					<td><%= @book_find.body %></td>
          <%= render 'favorites/btn', book_find: @book_find %>
          <!--コメント-->
          <td>
          	<p class="comment-count">コメント数：<%= @book_find.comments.count %></p>
          </td>
          <!--コメントここまで-->
					<% if @book_find.user.id == current_user.id %>
					<td><%= link_to "Edit", edit_book_path(@book_find.id), class: "btn-sm btn-success" %></td>
					<td><%= link_to "Destroy", book_path(@book_find), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
				  <% end %>
				</tr>
			</table>
	</div>
	<!--コメント一覧-->
	<div class="col-xs-9">
		<table class="commwnt-table">
    <% @comments.each do |comment| %>
      <tr>
      	<td><%= attachment_image_tag comment.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg" %></br>
      	  <%= comment.user.name %>
      	</td>
      	<td><%= comment.comment %></td>
      	<% if comment.user == current_user %>
      	<td><%= link_to 'Delete', book_comment_path(comment.book.id,comment.id), method: :delete, class: "btn btn-danger" %></td>
      	<% end %>
      </tr>
    <% end %>
    </table>
  </div>

  <%= render 'layouts/errors', book: @book_comment %>
	<!--コメント箱-->
	<div class="col-xs-9">
		<%= form_with(model:[@book_find, @book_comment]) do |f| %>
	    <%= f.text_area :comment, class: 'col-xs-11 book_body' %>
	    <%= f.submit '送信', class: "btn btn-xs btn-base-1 mt-20 pull-left" %>
    <% end %>
	</div>

</div>

app/views/favorites/_btn.html.erb
<!--いいね-->
					<% if book_find.favorited_by?(current_user) %>
          <td>
            <%= link_to book_favorites_path(book_find), method: :delete do %>
            <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
            <%= book_find.favorites.count %>
            <% end %>
					</td>
					<% else %>
					<td>
						<%= link_to book_favorites_path(book_find), method: :post do %>
            <i class="fa fa-heart" aria-hidden="true" ></i>
            <%= book_find.favorites.count %>
            <% end %>
					</td>
					<% end %>
          <!--いいねここまで-->

app/views/homes/about.html.erb
<h1>Welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>!</h1>

app/views/homes/top.html.erb
<div class="row">
  <div class='top-message col-xs-offset-3 col-xs-6'>
    <h1>welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>  !!</h1>
    <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
    <p>you can share and exchange  your opinions , inpressions , and emotions</p>
    <p> about various books!</p>

    <div class="btn-wrapper">
      <div class="row">
        <p><%= link_to 'Log in', new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
      </div>
      <div class="row">
        <p><%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
      </div>
    </div>


  </div>
</div>

app/views/layouts/_errors.html.erb
<% if book.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(book.errors.count, "error") %> prohibited this obj from being saved:</h3>

    <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-static-top navbar-inverse">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
          <li><%= link_to ' Books', books_path, class: 'glyphicon glyphicon-book books'%></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
        <% else %>
          <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' About', about_path, class: 'glyphicon glyphicon-link about' %></li>
          <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
          <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in'%></li>
        <% end %>
      </ul>
    </nav>

  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2-debug</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script
      src="https://kit.fontawesome.com/3813327bf4.js"
      crossorigin="anonymous"
    ></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <p id="notice"><%= notice %></p>

      <%= yield %>

    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.following.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_profile.html.erb
<table class="table">

	<tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>

	<tr>
		<th>follows</th>
		<th><%= link_to user.following.count, following_user_path(user) %></th>
	</tr>

	<tr>
		<th>followers</th>
		<th><%= link_to user.followers.count, followers_user_path(user) %></th>
	</tr>

</table>

<div class="row">
    <!--他ユーザーのプロフィールの場合、フォローボタンが表示される-->
    <% if user.id != current_user.id %>
      <!--フォロしている？-->
      <% if current_user.following?(user) %>
        <%= link_to "フォロー解除", user_relationships_path(user.id), method: :delete, class: "btn-sm btn-danger" %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn-sm btn-success" %>
      <% end %>
    <% end %>
</div>

<div class="row">

    <%= link_to '', edit_user_path(user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>

</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_with model:@user, local: true do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/followers.html.erb
<h2>Follower Users</h2>

<% if @user.followers.count != 0 %>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @user.followers.each do |user| %>
    <tr>
      <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
      <td><%= user.name %></td>
      <td>フォロー数：<%= user.following.count %></td>
      <td>フォロワー数：<%= user.followers.count %></td>
      <td><%= link_to "show", user_path(user.id) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<p>ユーザーはいません。</p>
<% end %>

app/views/users/following.html.erb
<h2>Follow Users</h2>

<% if @user.following.count != 0 %>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @user.following.each do |user| %>
    <tr>
      <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
      <td><%= user.name %></td>
      <td>フォロー数：<%= user.following.count %></td>
      <td>フォロワー数：<%= user.followers.count %></td>
      <td><%= link_to "show", user_path(user.id) %></td>
    </tr>
    <% end %>
  </tbody>
  <% else %>
    <p>ユーザーはいません</p>
  <% end %>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">

    <h2>User info</h2>
    <%= render 'users/profile', user: current_user %>

    <h2>New book</h2>
    <%= render 'books/form', book: @book %>
  </div>

  <div class="col-xs-9">
    <h2>Users</h2>
    <!--users一覧 -->
    <table class="table">
  	  <thead>
    		<tr>
	    		<th>image</th>
		    	<th>name</th>
			    <th colspan="3"></th>
  		  </tr>
  	  </thead>

    	<tbody>
  		  <% @users.each do |user| %>
	  	  <tr>
		  	  <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			    <td><%= user.name %></td>
			    <td>フォロー数：<%= user.following.count %></td>
          <td>フォロワー数：<%= user.followers.count %></td>
          <td>
            <% if user.id != current_user.id %>
              <% if current_user.following?(user) %>
                <%= link_to "フォロー解除", user_relationships_path(user.id), method: :delete, class: "btn-sm btn-danger" %>
              <% else %>
                <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn-sm btn-danger" %>
              <% end %>
            <% end %>
          </td>
			    <td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
		    </tr>
		    <% end %>
	    </tbody>
    </table>
<!--users一覧 -->
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/form', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>